#!/usr/bin/php

<?php

require_once "/Users/Coderockr/Dev/planrockr/Backend/vendor/autoload.php";

use PreCommit\Composer\Script\CodeQualityTool;

$console = new CodeQualityTool('Code Quality Tool', '1.0.0');
$console->run();
