#!/usr/bin/php

<?php

$fileDir = dirname(dirname(__FILE__));
$vendorDir = dirname(dirname($fileDir));

define('VENDOR_DIR', $vendorDir);

require_once VENDOR_DIR.DIRECTORY_SEPARATOR.'autoload.php';

use PreCommit\Composer\Script\CodeQualityTool;

$console = new CodeQualityTool('Code Quality Tool', '1.0.0');
$console->run();
